# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.ranking_by_tick_count_response import RankingByTickCountResponse
from openapi_client import configuration


class TestRankingByTickCountResponse(unittest.TestCase):
    """RankingByTickCountResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
