# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ApiSoftLimitResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            Stock = schemas.Float64Schema
            Margin = schemas.Float64Schema
            Future = schemas.Float64Schema
            FutureMini = schemas.Float64Schema
            Option = schemas.Float64Schema
            KabuSVersion = schemas.StrSchema
            __annotations__ = {
                "Stock": Stock,
                "Margin": Margin,
                "Future": Future,
                "FutureMini": FutureMini,
                "Option": Option,
                "KabuSVersion": KabuSVersion,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Stock"]) -> MetaOapg.properties.Stock: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Margin"]) -> MetaOapg.properties.Margin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Future"]) -> MetaOapg.properties.Future: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FutureMini"]) -> MetaOapg.properties.FutureMini: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Option"]) -> MetaOapg.properties.Option: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["KabuSVersion"]) -> MetaOapg.properties.KabuSVersion: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Stock", "Margin", "Future", "FutureMini", "Option", "KabuSVersion", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Stock"]) -> typing.Union[MetaOapg.properties.Stock, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Margin"]) -> typing.Union[MetaOapg.properties.Margin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Future"]) -> typing.Union[MetaOapg.properties.Future, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FutureMini"]) -> typing.Union[MetaOapg.properties.FutureMini, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Option"]) -> typing.Union[MetaOapg.properties.Option, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["KabuSVersion"]) -> typing.Union[MetaOapg.properties.KabuSVersion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Stock", "Margin", "Future", "FutureMini", "Option", "KabuSVersion", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        Stock: typing.Union[MetaOapg.properties.Stock, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        Margin: typing.Union[MetaOapg.properties.Margin, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        Future: typing.Union[MetaOapg.properties.Future, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        FutureMini: typing.Union[MetaOapg.properties.FutureMini, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        Option: typing.Union[MetaOapg.properties.Option, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        KabuSVersion: typing.Union[MetaOapg.properties.KabuSVersion, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApiSoftLimitResponse':
        return super().__new__(
            cls,
            *_args,
            Stock=Stock,
            Margin=Margin,
            Future=Future,
            FutureMini=FutureMini,
            Option=Option,
            KabuSVersion=KabuSVersion,
            _configuration=_configuration,
            **kwargs,
        )
