# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ExchangeResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            Symbol = schemas.StrSchema
            BidPrice = schemas.Float64Schema
            Spread = schemas.Float64Schema
            AskPrice = schemas.Float64Schema
            Change = schemas.Float64Schema
            Time = schemas.StrSchema
            __annotations__ = {
                "Symbol": Symbol,
                "BidPrice": BidPrice,
                "Spread": Spread,
                "AskPrice": AskPrice,
                "Change": Change,
                "Time": Time,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Symbol"]) -> MetaOapg.properties.Symbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["BidPrice"]) -> MetaOapg.properties.BidPrice: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Spread"]) -> MetaOapg.properties.Spread: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AskPrice"]) -> MetaOapg.properties.AskPrice: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Change"]) -> MetaOapg.properties.Change: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Time"]) -> MetaOapg.properties.Time: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Symbol", "BidPrice", "Spread", "AskPrice", "Change", "Time", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Symbol"]) -> typing.Union[MetaOapg.properties.Symbol, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["BidPrice"]) -> typing.Union[MetaOapg.properties.BidPrice, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Spread"]) -> typing.Union[MetaOapg.properties.Spread, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AskPrice"]) -> typing.Union[MetaOapg.properties.AskPrice, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Change"]) -> typing.Union[MetaOapg.properties.Change, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Time"]) -> typing.Union[MetaOapg.properties.Time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Symbol", "BidPrice", "Spread", "AskPrice", "Change", "Time", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        Symbol: typing.Union[MetaOapg.properties.Symbol, str, schemas.Unset] = schemas.unset,
        BidPrice: typing.Union[MetaOapg.properties.BidPrice, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        Spread: typing.Union[MetaOapg.properties.Spread, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        AskPrice: typing.Union[MetaOapg.properties.AskPrice, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        Change: typing.Union[MetaOapg.properties.Change, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        Time: typing.Union[MetaOapg.properties.Time, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ExchangeResponse':
        return super().__new__(
            cls,
            *_args,
            Symbol=Symbol,
            BidPrice=BidPrice,
            Spread=Spread,
            AskPrice=AskPrice,
            Change=Change,
            Time=Time,
            _configuration=_configuration,
            **kwargs,
        )
