# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class RankingByMarginResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            Type = schemas.StrSchema
            ExchangeDivision = schemas.StrSchema
            
            
            class Ranking(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            class properties:
                                _false = schemas.Int32Schema
                                Symbol = schemas.StrSchema
                                SymbolName = schemas.StrSchema
                                SellRapidPaymentPercentage = schemas.Float64Schema
                                SellLastWeekRatio = schemas.Float64Schema
                                BuyRapidPaymentPercentage = schemas.Float64Schema
                                BuyLastWeekRatio = schemas.Float64Schema
                                Ratio = schemas.Float64Schema
                                ExchangeName = schemas.StrSchema
                                CategoryName = schemas.StrSchema
                                __annotations__ = {
                                    "false": _false,
                                    "Symbol": Symbol,
                                    "SymbolName": SymbolName,
                                    "SellRapidPaymentPercentage": SellRapidPaymentPercentage,
                                    "SellLastWeekRatio": SellLastWeekRatio,
                                    "BuyRapidPaymentPercentage": BuyRapidPaymentPercentage,
                                    "BuyLastWeekRatio": BuyLastWeekRatio,
                                    "Ratio": Ratio,
                                    "ExchangeName": ExchangeName,
                                    "CategoryName": CategoryName,
                                }
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["false"]) -> MetaOapg.properties._false: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["Symbol"]) -> MetaOapg.properties.Symbol: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["SymbolName"]) -> MetaOapg.properties.SymbolName: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["SellRapidPaymentPercentage"]) -> MetaOapg.properties.SellRapidPaymentPercentage: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["SellLastWeekRatio"]) -> MetaOapg.properties.SellLastWeekRatio: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["BuyRapidPaymentPercentage"]) -> MetaOapg.properties.BuyRapidPaymentPercentage: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["BuyLastWeekRatio"]) -> MetaOapg.properties.BuyLastWeekRatio: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["Ratio"]) -> MetaOapg.properties.Ratio: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["ExchangeName"]) -> MetaOapg.properties.ExchangeName: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["CategoryName"]) -> MetaOapg.properties.CategoryName: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["false", "Symbol", "SymbolName", "SellRapidPaymentPercentage", "SellLastWeekRatio", "BuyRapidPaymentPercentage", "BuyLastWeekRatio", "Ratio", "ExchangeName", "CategoryName", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["false"]) -> typing.Union[MetaOapg.properties._false, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["Symbol"]) -> typing.Union[MetaOapg.properties.Symbol, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["SymbolName"]) -> typing.Union[MetaOapg.properties.SymbolName, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["SellRapidPaymentPercentage"]) -> typing.Union[MetaOapg.properties.SellRapidPaymentPercentage, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["SellLastWeekRatio"]) -> typing.Union[MetaOapg.properties.SellLastWeekRatio, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["BuyRapidPaymentPercentage"]) -> typing.Union[MetaOapg.properties.BuyRapidPaymentPercentage, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["BuyLastWeekRatio"]) -> typing.Union[MetaOapg.properties.BuyLastWeekRatio, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["Ratio"]) -> typing.Union[MetaOapg.properties.Ratio, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["ExchangeName"]) -> typing.Union[MetaOapg.properties.ExchangeName, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["CategoryName"]) -> typing.Union[MetaOapg.properties.CategoryName, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["false", "Symbol", "SymbolName", "SellRapidPaymentPercentage", "SellLastWeekRatio", "BuyRapidPaymentPercentage", "BuyLastWeekRatio", "Ratio", "ExchangeName", "CategoryName", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, ],
                            Symbol: typing.Union[MetaOapg.properties.Symbol, str, schemas.Unset] = schemas.unset,
                            SymbolName: typing.Union[MetaOapg.properties.SymbolName, str, schemas.Unset] = schemas.unset,
                            SellRapidPaymentPercentage: typing.Union[MetaOapg.properties.SellRapidPaymentPercentage, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                            SellLastWeekRatio: typing.Union[MetaOapg.properties.SellLastWeekRatio, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                            BuyRapidPaymentPercentage: typing.Union[MetaOapg.properties.BuyRapidPaymentPercentage, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                            BuyLastWeekRatio: typing.Union[MetaOapg.properties.BuyLastWeekRatio, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                            Ratio: typing.Union[MetaOapg.properties.Ratio, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                            ExchangeName: typing.Union[MetaOapg.properties.ExchangeName, str, schemas.Unset] = schemas.unset,
                            CategoryName: typing.Union[MetaOapg.properties.CategoryName, str, schemas.Unset] = schemas.unset,
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                *_args,
                                Symbol=Symbol,
                                SymbolName=SymbolName,
                                SellRapidPaymentPercentage=SellRapidPaymentPercentage,
                                SellLastWeekRatio=SellLastWeekRatio,
                                BuyRapidPaymentPercentage=BuyRapidPaymentPercentage,
                                BuyLastWeekRatio=BuyLastWeekRatio,
                                Ratio=Ratio,
                                ExchangeName=ExchangeName,
                                CategoryName=CategoryName,
                                _configuration=_configuration,
                                **kwargs,
                            )
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]], typing.List[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Ranking':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "Type": Type,
                "ExchangeDivision": ExchangeDivision,
                "Ranking": Ranking,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Type"]) -> MetaOapg.properties.Type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ExchangeDivision"]) -> MetaOapg.properties.ExchangeDivision: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Ranking"]) -> MetaOapg.properties.Ranking: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Type", "ExchangeDivision", "Ranking", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Type"]) -> typing.Union[MetaOapg.properties.Type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ExchangeDivision"]) -> typing.Union[MetaOapg.properties.ExchangeDivision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Ranking"]) -> typing.Union[MetaOapg.properties.Ranking, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Type", "ExchangeDivision", "Ranking", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        Type: typing.Union[MetaOapg.properties.Type, str, schemas.Unset] = schemas.unset,
        ExchangeDivision: typing.Union[MetaOapg.properties.ExchangeDivision, str, schemas.Unset] = schemas.unset,
        Ranking: typing.Union[MetaOapg.properties.Ranking, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RankingByMarginResponse':
        return super().__new__(
            cls,
            *_args,
            Type=Type,
            ExchangeDivision=ExchangeDivision,
            Ranking=Ranking,
            _configuration=_configuration,
            **kwargs,
        )
