# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)  # noqa: E501

    The version of the OpenAPI document: 1.5
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.cancelorder.put import CancelorderPut
from openapi_client.paths.sendorder_future.post import SendoderFuturePost
from openapi_client.paths.sendorder_option.post import SendorderOptionPost
from openapi_client.paths.sendorder.post import SendorderPost


class OrderApi(
    CancelorderPut,
    SendoderFuturePost,
    SendorderOptionPost,
    SendorderPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
